name: Run iOS

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node modules
        run: |
          yarn install
      - name: Cache Yarn Deps
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
      - name: Cache Pods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-
      - name: Update Pods
        working-directory: ./ios
        run: |
          pod install
      - name: Run test
        run: |
          yarn jest
      - name: Run iOS
        run: |
          yarn ios
