name: Run Android

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node modules
        run: |
          yarn install
      - name: Cache Yarn Deps
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
      - name: Run test
        run: |
          yarn jest
      - name: Run Android
        run: |
          yarn android
